[project]
name = "rpi-sonsor-client"
version = "0.1.0"
description = "Sensor client for Raspberry Pi"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.12.7",
]
